### PR TITLE
feat: eslint-plugin-case-police

### PR DESCRIPTION
**Pull request by jaw52**
> Please read the [Contributions Guide](https://github.com/antfu/case-police/blob/main/CONTRIBUTING.md) before making Pull Requests.

feat `eslint-plugin-case-police`

The effect is as follows

GIF

Also supports template string
GIF 2023-4-6 12-33-22

current rules

- Check the correctness of the string

For https://github.com/antfu/case-police/issues/116

### CODE REVIEW

**Comment by jaw52** [comment]
Now also supports template string
GIF 2023-4-6 12-33-22

**Comment by jaw52** [comment]
The configuration options are the same as for the cli

**Comment by jaw52** [comment]
I think I will use this to make a plugin for VS Code

**Comment by jaw52** [comment]
Hi @antfu , I hope this message finds you well. Is there anything more I can do to help move it along?  Thank you for your time.

**Comment by jaw52** [comment]
image
image
Add `case-police` for vue and jsx

**Comment by antfu** [comment]
Do we really need a VS Code plugin if ESLint is already able to handle it?

**Comment by jaw52** [comment]
> Do we really need a VS Code plugin if ESLint is already able to handle it?

I'm not sure if anyone needs it, so I haven't finished the vscode plugin. I can then remove the vscode plugin for now

**Comment by antfu** [comment]
I see. Let's focus on ESLint plugin first :) - Ping me when you are done and I will start reviewing. Thanks!

**Comment by jaw52** [comment]
> I see. Let's focus on ESLint plugin first :) - Ping me when you are done and I will start reviewing. Thanks!

OK, the vscode plugin has been temporarily removed. The review is ready to begin

**Pull request merged**
